export declare const LIB_OAK_DOMAIN = "oak-domain";
export declare const LIB_PATH: () => string;
export declare const ENTITY_PATH_IN_OAK_GENERAL_BUSINESS: () => string;
export declare const ENTITY_PATH_IN_OAK_DOMAIN: () => string;
export declare const TYPE_PATH_IN_OAK_DOMAIN: (level?: number) => string;
export declare const ACTION_CONSTANT_IN_OAK_DOMAIN: (level?: number) => string;
export declare const RESERVED_ENTITY_NAMES: string[];
export declare const ENTITY_NAME_MAX_LENGTH = 32;
export declare const STRING_LITERAL_MAX_LENGTH = 24;
export declare const NUMERICAL_LITERL_DEFAULT_PRECISION = 8;
export declare const NUMERICAL_LITERL_DEFAULT_SCALE = 2;
export declare const INT_LITERL_DEFAULT_WIDTH = 4;
export declare const SYSTEM_RESERVE_ENTITIES: string[];
export declare const OAK_EXTERNAL_LIBS_FILEPATH: (path: string) => string;
