"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NUMERICAL_LITERL_DEFAULT_SCALE = exports.NUMERICAL_LITERL_DEFAULT_PRECISION = exports.STRING_LITERAL_MAX_LENGTH = exports.RESERVED_ENTITIES = exports.OUTPUT_PATH = exports.ACTION_CONSTANT_IN_OAK_DOMAIN = exports.ELEMENT_PATH_IN_OAK_DOMAIN = exports.ENTITY_PATH_IN_OAK_DOMAIN = exports.ROOT_PATH_IN_OAK_DOMAIN = exports.LIB_OAK_DOMAIN = void 0;
exports.LIB_OAK_DOMAIN = 'oak-domain';
exports.ROOT_PATH_IN_OAK_DOMAIN = process.env.NODE_ENV === 'development' ? 'src' : 'lib';
exports.ENTITY_PATH_IN_OAK_DOMAIN = `${exports.LIB_OAK_DOMAIN}/${exports.ROOT_PATH_IN_OAK_DOMAIN}/entities/`;
exports.ELEMENT_PATH_IN_OAK_DOMAIN = `${exports.LIB_OAK_DOMAIN}/${exports.ROOT_PATH_IN_OAK_DOMAIN}/elements/`;
exports.ACTION_CONSTANT_IN_OAK_DOMAIN = `${exports.LIB_OAK_DOMAIN}/${exports.ROOT_PATH_IN_OAK_DOMAIN}/actions/action`;
exports.OUTPUT_PATH = 'app-domain/entities';
exports.RESERVED_ENTITIES = ['Schema', 'Filter', 'Query', 'SubQuery', 'Entity', 'Selection', 'Operation', 'File'];
exports.STRING_LITERAL_MAX_LENGTH = 16;
exports.NUMERICAL_LITERL_DEFAULT_PRECISION = 8;
exports.NUMERICAL_LITERL_DEFAULT_SCALE = 2;
