import { EntityDef as ActionAuth } from "./ActionAuth/Schema";
import { EntityDef as DirectActionAuth } from "./DirectActionAuth/Schema";
import { EntityDef as DirectRelationAuth } from "./DirectRelationAuth/Schema";
import { EntityDef as FreeActionAuth } from "./FreeActionAuth/Schema";
import { EntityDef as Modi } from "./Modi/Schema";
import { EntityDef as ModiEntity } from "./ModiEntity/Schema";
import { EntityDef as Oper } from "./Oper/Schema";
import { EntityDef as OperEntity } from "./OperEntity/Schema";
import { EntityDef as Relation } from "./Relation/Schema";
import { EntityDef as RelationAuth } from "./RelationAuth/Schema";
import { EntityDef as User } from "./User/Schema";
import { EntityDef as UserEntityGrant } from "./UserEntityGrant/Schema";
import { EntityDef as UserRelation } from "./UserRelation/Schema";
export declare type EntityDict = {
    actionAuth: ActionAuth;
    directActionAuth: DirectActionAuth;
    directRelationAuth: DirectRelationAuth;
    freeActionAuth: FreeActionAuth;
    modi: Modi;
    modiEntity: ModiEntity;
    oper: Oper;
    operEntity: OperEntity;
    relation: Relation;
    relationAuth: RelationAuth;
    user: User;
    userEntityGrant: UserEntityGrant;
    userRelation: UserRelation;
};
