"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.initinctiveAttributes = exports.SeqAttribute = exports.DeleteAtAttribute = exports.UpdateAtAttribute = exports.CreateAtAttribute = exports.PrimaryKeyAttribute = exports.TriggerUuidAttribute = exports.TriggerDataAttribute = void 0;
exports.TriggerDataAttribute = '$$triggerData$$';
exports.TriggerUuidAttribute = '$$triggerUuid$$';
exports.PrimaryKeyAttribute = 'id';
exports.CreateAtAttribute = '$$createAt$$';
exports.UpdateAtAttribute = '$$updateAt$$';
exports.DeleteAtAttribute = '$$deleteAt$$';
exports.SeqAttribute = '$$seq$$';
exports.initinctiveAttributes = [exports.PrimaryKeyAttribute, exports.TriggerDataAttribute, exports.TriggerUuidAttribute, exports.CreateAtAttribute, exports.UpdateAtAttribute, exports.DeleteAtAttribute, exports.SeqAttribute];
;
;
;
;
